# Site settings
title: 雪柳漫天
SEOTitle: 雪柳漫天的博客 | zbianc's Blog
header-img: img/post-bg-desk2.jpg
email: zbianc@163.com
description: "Always Curious About the World"
keyword: "zbianc, zbianc's Blog, 雪柳漫天的博客, CFD, 跨介质, 入水, 跨介质航行力学"
url: "http://zbianc.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zbianc/zbianc.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Muss Es Sein?"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:   zbianc1993
neteasemusic_username:     61680227
github_username:    zbianc
CSDN_username:  zbianc
# jianshu_username:   e71990ada2fd
bilibili_username:   7354541




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 6b832577e630254d95d2                            #生成的clientID
  clientSecret: 414ec6dd9a4644f89ceb89be1f8d0c13e66afe46    #生成的clientSecret
  repo: zbianc.github.io    #仓库名称
  owner: zbianc    #github用户名
  admin: zbianc
  id: 'window.location.pathname'
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: cc9870a43d78207c4ec9c39be629d88e

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "跨介质飞行力学实验室",
        href: "http://www.sd402.com"
    },{
        title: "东岳流体",
        href: "http://dyfluid.com"
    },{
        title: "CFD中文网",
        href: "http://www.cfd-china.com"
    },{
        title: "图灵社区",
        href: "https://www.ituring.com.cn"
    }
]
